[package]
name = "lua51"
version = "0.1.0"
authors = ["Chris Bajorin <chris@chrisbajorin.com>"]
edition = "2018"
build = "build.rs"

[lib]
name = "lua51"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.5.2"

[dependencies]
common = { path = "../common", features = ["lua51"]}
